#!/usr/bin/perl -Iblib/lib

BEGIN {
    my @mtime = map {(stat $_)[9]} qw(Makefile Makefile.PL);
    system (qw(perl Makefile.PL)) if $mtime[0] != $mtime[1];
    system (qw(make -f Makefile));
}

use strict;
use Math::Business::HMA;
use GD::Graph::mixed;
use List::Util qw(min max);

my $hma = Math::Business::HMA->new(12);
my @points = qw(
    7 4 11 4 11 7 8 3 6 10 11 9 10 6 9 4 5 7 6 6 8 8 5 3 6 6 9 3 10 4 5 10 4 8 4 8 3 3 8 8 3 10 3 5 11 3
    11 8 6 7 4 3 11 11 6 10 11 6 4 3 6 5 10 9 4 10 4 5 6 4 3 7 4 4 6 7 4 7 10 5 6 8 10 11 10 11 11 3 3 9
    10 5 4 6 5 11 10 6 10 3 5 3 5 7 11 6 11 4 6 4 7 11 8 7 8 10 5 9 11 3 11 9 10 3 4 5 7 8 5 10 5 3 6 9
    4 10 10 10 7 3 8 8 8 5 10 9 11 6 11 8 3 10 4 8 5 7 6 6 11 6 6 8 6 5 9 11 7 4 3 7 6 3 5 3 8 10 11 8 10
    10 4 7 9 6 4 8 6 3 9 7 4 7 5 11 5 10 6 4 6 3 11 3 3 5 10 5 11 8 9 9 9 4 8 9 9 11 7 9 9 8 10 4 5 6 11
    5 6 8 7 3 7 8 4 11 10 11 6 11 7 4 10 4 8 7 11 8 11 9 5 8 7 5 6 8 3 9 11 4 11 3 7 7 9 4
);

my @data;
for my $p (0 .. $#points) {
    $hma->insert($points[$p]);

    my $x = 0;
    push @{$data[$x++]}, $p;
    push @{$data[$x++]}, $points[$p];
    push @{$data[$x++]}, $hma->query;
}

my @all_points = grep {defined $_} map {ref $_ ? @$_ : $_} map {@$_} @data[1 .. $#data];
my $min_point  = min(@all_points);
my $max_point  = max(@all_points);

my $graph = GD::Graph::mixed->new(1000, 500);
   $graph->set(
       y_label           => 'dollars',
       x_label           => 'date',
       transparent       => 0,
       markers           => [qw(8)],
       dclrs             => [qw(lblue lred)],
       types             => [qw(points lines)],
       y_min_value       => $min_point-0.2,
       y_max_value       => $max_point+0.2,
       y_number_format   => '%0.2f',
       x_labels_vertical => 1,

   ) or die $graph->error;

my $gd = $graph->plot(\@data) or die $graph->error;
open my $img, '>', "graph.png" or die $!;
binmode $img;
print $img $gd->png;
close $img;

system(qw(eog graph.png));

__END__
This controls the order of markers in points and linespoints graphs.  This should be a reference to an array of
numbers:

    $graph->set( markers => [3, 5, 6] );

Available markers are: 1: filled square, 2: open square, 3: horizontal cross, 4: diagonal cross, 5: filled dia-
mond, 6: open diamond, 7: filled circle, 8: open circle, 9: horizontal line, 10: vertical line.  Note that the
last two are not part of the default list.

Default: [1,2,3,4,5,6,7,8]
