=head1 NAME

Math::Business::StockMonkey - Base documentation for the StockMonkey Collection

=head1 SYNOPSIS

The stockmonkey distribution is supposed to contain all the technical analysis
tools you'd ever want.  It has a few things, but it's sadly lacking.

If you'd like to help, just let me know.

Links to the algorithm are helpful as our spreadsheets with example
calculations.

=head1 MODULES

L<Math::Business::SMA> - Simple Moving Average

L<Math::Business::EMA> - Exponential Moving Average

L<Math::Business::MACD> - Moving Average Convergence/Divergence

L<Math::Business::RSI> - Relative Strength Index

L<Math::Business::BollingerBands> - Bollinger Bands

=head1 AUTHOR

Paul Miller <jettero@cpan.org>

I am using this software in my own projects...  If you find bugs, please please
please let me know.

I normally hang out on #perl on freenode, so you can try to get immediate
gratification there if you like.  L<irc://irc.freenode.net/perl>

=head1 COPYRIGHT

Copyright (c) 2008 Paul Miller -- LGPL [Software::License::LGPL_2_1]

    perl -MSoftware::License::LGPL_2_1 \
         -e '$l = Software::License::LGPL_2_1->new({
             holder=>"Paul Miller"});
             print $l->fulltext' | less
